on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: ssh deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: web01-instituto.hostmundi.com
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          remotePath: ${{ secrets.REMOTE_TARGET }}
